# Generated by Django 5.1 on 2025-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CFE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='empleados_asignados',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='empleados_asignados',
            field=models.ManyToManyField(related_name='domicilios', to='app_CFE.empleado'),
        ),
    ]
