# Generated by Django 5.2.6 on 2025-11-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_CFE', '0002_remove_domicilio_empleados_asignados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='empleadorio',
            new_name='salario',
        ),
    ]
